### ISSUE TITLE
sOlid

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/sequelize-model#1]
https://github.com/DenisPitsul/sequelize-model/blob/f30dcb2a9308e1110454c599f83c353437e475e1/controllers/phonesController.js#L52
https://github.com/DenisPitsul/sequelize-model/blob/f30dcb2a9308e1110454c599f83c353437e475e1/controllers/phonesController.js#L91
- тут можна на перезаписувати повністю все, а додати чого не вистачає і видалити зайве. Інакше, якщо доведеться додавати або прибирати властивості з `phone`, то доведеться корегувати ці рядки.

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/sequelize-model/commit/1642d50c2860882d525ab97904165c746a943fd8
